menu:
    About: /about/
    Contact: /contact/
    Archive: /archives/
    GitHub: https://github.com/vinceg
    Rss: /rss.xml

favicon:
logo:

# Comment
# e.g disqus: seansun
disqus: vadimsblog
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2015
